name: Package Aurora Echo

on:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Packaging
      run: |
        pip install pipenv
        make release

    - uses: actions/upload-artifact@v4
      with:
        name: aurora-echo
        path: dist/

    - if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*